name: Fetch Competitions

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  fetch-competitions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install axios
        run: npm install axios

      - name: Fetch competitions and save to file
        run: |
          node <<'EOF'
          const fs = require('fs');
          const axios = require('axios');

          axios.get('https://inschrijven.schaatsen.nl/api/competitions')
            .then(response => {
              const competitions = response.data.filter(c => 
                c.competitors && c.competitors.some(comp => comp.id === 10236341)
              );
              fs.mkdirSync('./data', { recursive: true });
              fs.writeFileSync('./data/competitions.json', JSON.stringify(competitions, null, 2));
              console.log('Competitions saved to data/competitions.json');
            })
            .catch(error => {
              console.error('Error fetching competitions:', error);
              process.exit(1);
            });
          EOF

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/competitions.json
          git commit -m "Update competitions.json"
          git push
